name: Apply

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -upgrade
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate
      - uses: /eticket-app/.github/workflows/docker-build-deploy.yml
        using: /eticket-app/.github/workflows/docker-build-deploy.yml
      - uses: /stickynotes-app/.github/workflows/docker-build-deploy.yml
        using: /stickynotes-app/.github/workflows/docker-build-deploy.yml
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
      