name: Terraform Plan

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  AWS_REGION: ap-south-1

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------
      # Checkout
      # ---------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------------------------------------
      # AWS Credentials
      # ---------------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ---------------------------------------------
      # Terraform
      # ---------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # ---------------------------------------------
      # Terraform Init
      # ---------------------------------------------
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      # ---------------------------------------------
      # Terraform Validate
      # ---------------------------------------------
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      # ---------------------------------------------
      # Terraform Plan
      # ---------------------------------------------
      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan \
            -input=false \
            -out=tfplan \
            -var="image_tag=${GITHUB_SHA}"

      # ---------------------------------------------
      # Show Plan
      # ---------------------------------------------
      - name: Terraform Show
        working-directory: terraform
        run: terraform show -no-color tfplan

      # ---------------------------------------------
      # Verify Plan
      # ---------------------------------------------
      - name: Verify Terraform Plan
        working-directory: terraform
        run: |
          test -f tfplan

          echo "Terraform plan created successfully:"
          ls -lh tfplan

      # ---------------------------------------------
      # Upload Exact Plan
      # ---------------------------------------------
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.sha }}
          path: terraform/tfplan
          if-no-files-found: error
          retention-days: 1