name: Terraform Plan

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

env:
  AWS_REGION: ap-south-1

jobs:
  plan-and-filter:
    name: Terraform Plan & Out File Generation
    runs-on: ubuntu-latest
    
    outputs:
      eticket_changed: ${{ steps.filter.outputs.eticket }}
      stickynotes_changed: ${{ steps.filter.outputs.stickynotes }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Path Filter Configuration
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ github.event.before || 'HEAD~1' }}
          filters: |
            eticket:
              - 'eticket-app/**'
            stickynotes:
              - 'stickynotes-app/**'

      - name: Save changes status file
        run: |
          mkdir -p diff-status
          echo "${{ steps.filter.outputs.eticket }}" > diff-status/eticket.txt
          echo "${{ steps.filter.outputs.stickynotes }}" > diff-status/stickynotes.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Plan Out
        working-directory: terraform
        run: |
          terraform init -input=false
          terraform plan -input=false -out=tfplan

      - name: Upload Plan Out File & Diffs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.sha }}
          path: |
            terraform/tfplan
            diff-status/
     

